package types

type Message struct {
	MessageId            int             `json:"message_id"`
	From                 User            `json:"from"`
	SenderChat           Chat            `json:"sender_chat"`
	Date                 int             `json:"date"`
	Chat                 Chat            `json:"chat"`
	ForwardFrom          User            `json:"forward_from"`
	ForwardFromChat      Chat            `json:"forward_from_chat"`
	ForwardFromMessageId int             `json:"forward_from_message_id"`
	ForwardSignature     string          `json:"forward_signature"`
	ForwardSenderName    string          `json:"forward_sender_name"`
	ForwardDate          int             `json:"forward_date"`
	IsAutomaticForward   bool            `json:"is_automatic_forward"`
	ReplyToMessage       *Message        `json:"reply_to_message"`
	ViaBot               User            `json:"via_bot"`
	EditDate             int             `json:"edit_date"`
	HasProtectedContent  bool            `json:"has_protected_content"`
	MediaGroupId         int             `json:"media_group_id"`
	AuthorSignature      string          `json:"author_signature"`
	Text                 string          `json:"text"`
	Entities             []MessageEntity `json:"entities"`
	Animation            Animation       `json:"animation"`
	// TODO Audio
	// TODO Document
	// TODO Photo
	// TODO Sticker
	// TODO Video
	// TODO VideoNote
	// TODO Voice
	Caption         string          `json:"caption"`
	CaptionEntities []MessageEntity `json:"caption_entities"`
	// TODO Contact
	// TODO Dice
	// TODO Game
	// TODO Poll
	// TODO Venue
	// TODO Location
	NewChatMembers []User `json:"new_chat_members"`
	LeftChatMember User   `json:"left_chat_member"`
	NewChatTitle   string `json:"new_chat_title"`
	// TODO NewChatPhoto
	DeleteChatPhoto               bool                          `json:"delete_chat_photo"`
	GroupChatCreated              bool                          `json:"group_chat_created"`
	SupergroupChatCreated         bool                          `json:"supergroup_chat_created"`
	ChannelChatCreated            bool                          `json:"channel_chat_created"`
	MessageAutoDeleteTimerChanged MessageAutoDeleteTimerChanged `json:"message_auto_delete_timer_changed"`
	MigrateToChatId               int                           `json:"migrate_to_chat_id"`
	MigrateFromChatId             int                           `json:"migrate_from_chat_id"`
	PinnedMessage                 *Message                      `json:"pinned_message"`
	// TODO Invoice
	SuccessfulPayment            SuccessfulPayment            `json:"successful_payment"`
	ConnectedWebsite             string                       `json:"connected_website"`
	PassportData                 PassportData                 `json:"passport_data"`
	ProximityAlertTriggered      ProximityAlertTriggered      `json:"proximity_alert_triggered"`
	VideoChatScheduled           VideoChatScheduled           `json:"video_chat_scheduled"`
	VideoChatStarted             VideoChatStarted             `json:"video_chat_started"`
	VideoChatEnded               VideoChatEnded               `json:"video_chat_ended"`
	VideoChatParticipantsInvited VideoChatParticipantsInvited `json:"video_chat_participants_invited"`
	WebAppData                   WebAppData                   `json:"web_app_data"`
	ReplyMarkup                  InlineKeyboardMarkup         `json:"reply_markup"`
}
